spring:
  banner:
    image:
      location: banner.txt #自定义banner
  allowBeanDefinitionOverriding: true
  main:
    lazy-initialization: false
  devtools:
    restart:
      #默认就是true
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/yuyixi
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8081