version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins:2.263.1-lts-centos7
    container_name: my_jenkins
    ports:
      - "7070:8080"
      - "51000:50000"
    restart: always
    network_mode: "bridge"