version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'root'
      MYSQL_PASS: 'password'
    restart: always
    network_mode: "bridge"